/**
 * Build a single self-contained `index-preview.html` at the repo root.
 *
 * Bundles the real src/ (JS + CSS + Leaflet, marker images inlined as data
 * URLs) with esbuild, then injects it into the page markup from index.html.
 * The result opens standalone (needs internet only for map tiles + fonts) —
 * handy for sharing a live preview without running the dev server.
 *
 *   npm run preview:standalone
 *
 * Do not hand-edit index-preview.html — regenerate it with this script.
 */
import { build } from 'esbuild';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const r = (p) => resolve(root, p);

const result = await build({
  entryPoints: [r('src/main.js')],
  bundle: true,
  format: 'iife',
  write: false,
  define: { 'import.meta.env.DEV': 'false' },
  loader: { '.png': 'dataurl', '.svg': 'dataurl' },
  outdir: r('.'),
});

let js = '';
let css = '';
for (const f of result.outputFiles) {
  if (f.path.endsWith('.js')) js = f.text;
  else if (f.path.endsWith('.css')) css = f.text;
}
js = js.replace(/<\/script/gi, '<\\/script'); // guard against premature close

const html = readFileSync(r('index.html'), 'utf8');
const bodyInner = html
  .replace(/^[\s\S]*<body>/, '')
  .replace(/<\/body>[\s\S]*$/, '')
  .replace(/\s*<script type="module"[\s\S]*?<\/script>\s*/g, '\n')
  .trimEnd();

const fonts =
  '<link rel="preconnect" href="https://fonts.googleapis.com" />\n' +
  '    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />\n' +
  '    <link href="https://fonts.googleapis.com/css2?family=Hanken+Grotesk:wght@400;500;600;700&family=Sora:wght@400;500;600;700&display=swap" rel="stylesheet" />';

const out = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
    <meta name="color-scheme" content="light dark" />
    <title>GroundLink — Comms Coverage Planner (standalone preview)</title>
    <!-- Generated by scripts/build-preview.mjs from src/. Do not hand-edit. -->
    ${fonts}
    <style>
${css}
    </style>
  </head>
  <body>
${bodyInner}
    <script>
${js}
    </script>
  </body>
</html>
`;

writeFileSync(r('index-preview.html'), out);
console.log(`✓ index-preview.html — ${(out.length / 1024).toFixed(0)} kB (self-contained)`);
